/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BillingLogListResponse : Paginated billing logs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingLogListResponse {
    #[serde(rename = "logs")]
    pub logs: Vec<models::BillingLogResponse>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "page_size")]
    pub page_size: i32,
}

impl BillingLogListResponse {
    /// Paginated billing logs.
    pub fn new(logs: Vec<models::BillingLogResponse>, total: i32, page: i32, page_size: i32) -> BillingLogListResponse {
        BillingLogListResponse {
            logs,
            total,
            page,
            page_size,
        }
    }
}

