/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BillingLogResponse : Billing activity log entry.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingLogResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "monitor_id")]
    pub monitor_id: String,
    #[serde(rename = "monitor_name")]
    pub monitor_name: String,
    #[serde(rename = "billed_at")]
    pub billed_at: String,
    #[serde(rename = "num_accounts")]
    pub num_accounts: i32,
    #[serde(rename = "credits_deducted")]
    pub credits_deducted: f64,
    #[serde(rename = "tier_label")]
    pub tier_label: String,
    #[serde(rename = "rate_applied")]
    pub rate_applied: f64,
}

impl BillingLogResponse {
    /// Billing activity log entry.
    pub fn new(id: String, monitor_id: String, monitor_name: String, billed_at: String, num_accounts: i32, credits_deducted: f64, tier_label: String, rate_applied: f64) -> BillingLogResponse {
        BillingLogResponse {
            id,
            monitor_id,
            monitor_name,
            billed_at,
            num_accounts,
            credits_deducted,
            tier_label,
            rate_applied,
        }
    }
}

