/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColorsResponse : Envelope returned by the colour reference endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColorsResponse {
    #[serde(rename = "colors")]
    pub colors: Vec<models::VintedColor>,
}

impl ColorsResponse {
    /// Envelope returned by the colour reference endpoint.
    pub fn new(colors: Vec<models::VintedColor>) -> ColorsResponse {
        ColorsResponse {
            colors,
        }
    }
}

