/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtractRequest {
    /// The page to fetch.
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "wait_for", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wait_for: Option<Option<String>>,
    #[serde(rename = "country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country: Option<Option<String>>,
    /// Proxy pool: simple, premium or ultra.
    #[serde(rename = "proxy_tier", skip_serializing_if = "Option::is_none")]
    pub proxy_tier: Option<ProxyTier>,
    #[serde(rename = "extract_rules", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extract_rules: Option<Option<std::collections::HashMap<String, models::ExtractRequestExtractRulesValue>>>,
    #[serde(rename = "ai_extract_rules", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ai_extract_rules: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "ai_query", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ai_query: Option<Option<String>>,
    /// Render the page in a browser first.
    #[serde(rename = "render_js", skip_serializing_if = "Option::is_none")]
    pub render_js: Option<bool>,
}

impl ExtractRequest {
    pub fn new(url: String) -> ExtractRequest {
        ExtractRequest {
            url,
            wait_for: None,
            country: None,
            proxy_tier: None,
            extract_rules: None,
            ai_extract_rules: None,
            ai_query: None,
            render_js: None,
        }
    }
}
/// Proxy pool: simple, premium or ultra.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProxyTier {
    #[serde(rename = "simple")]
    Simple,
    #[serde(rename = "premium")]
    Premium,
    #[serde(rename = "ultra")]
    Ultra,
}

impl Default for ProxyTier {
    fn default() -> ProxyTier {
        Self::Simple
    }
}

