/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterRuleValidateResponse : Validation result for a Twitter search query.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterRuleValidateResponse {
    #[serde(rename = "valid")]
    pub valid: bool,
    #[serde(rename = "query")]
    pub query: String,
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<String>>,
}

impl FilterRuleValidateResponse {
    /// Validation result for a Twitter search query.
    pub fn new(valid: bool, query: String) -> FilterRuleValidateResponse {
        FilterRuleValidateResponse {
            valid,
            query,
            error: None,
        }
    }
}

