/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterRuleUpdate : Partial update filter rule request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterRuleUpdate {
    #[serde(rename = "tag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tag: Option<Option<String>>,
    #[serde(rename = "query", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub query: Option<Option<String>>,
    #[serde(rename = "interval_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interval_seconds: Option<Option<f64>>,
    #[serde(rename = "max_results_per_poll", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_results_per_poll: Option<Option<i32>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "webhook_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
    #[serde(rename = "webhook_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
}

impl FilterRuleUpdate {
    /// Partial update filter rule request.
    pub fn new() -> FilterRuleUpdate {
        FilterRuleUpdate {
            tag: None,
            query: None,
            interval_seconds: None,
            max_results_per_poll: None,
            status: None,
            webhook_url: None,
            webhook_secret: None,
        }
    }
}

