/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterRuleDeliveryLogResponse : Delivery log entry for a filter rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterRuleDeliveryLogResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "rule_id")]
    pub rule_id: String,
    #[serde(rename = "rule_tag")]
    pub rule_tag: String,
    #[serde(rename = "tweet_id")]
    pub tweet_id: String,
    #[serde(rename = "author_username")]
    pub author_username: String,
    #[serde(rename = "tweet_text_preview", deserialize_with = "Option::deserialize")]
    pub tweet_text_preview: Option<String>,
    #[serde(rename = "tweet_url")]
    pub tweet_url: String,
    #[serde(rename = "tweet_published_at")]
    pub tweet_published_at: String,
    #[serde(rename = "detected_at")]
    pub detected_at: String,
    #[serde(rename = "latency_ms")]
    pub latency_ms: i32,
    #[serde(rename = "latency_badge")]
    pub latency_badge: String,
    #[serde(rename = "delivery_status")]
    pub delivery_status: String,
    #[serde(rename = "webhook_status_code", deserialize_with = "Option::deserialize")]
    pub webhook_status_code: Option<i32>,
    #[serde(rename = "webhook_attempts")]
    pub webhook_attempts: i32,
}

impl FilterRuleDeliveryLogResponse {
    /// Delivery log entry for a filter rule.
    pub fn new(id: String, rule_id: String, rule_tag: String, tweet_id: String, author_username: String, tweet_text_preview: Option<String>, tweet_url: String, tweet_published_at: String, detected_at: String, latency_ms: i32, latency_badge: String, delivery_status: String, webhook_status_code: Option<i32>, webhook_attempts: i32) -> FilterRuleDeliveryLogResponse {
        FilterRuleDeliveryLogResponse {
            id,
            rule_id,
            rule_tag,
            tweet_id,
            author_username,
            tweet_text_preview,
            tweet_url,
            tweet_published_at,
            detected_at,
            latency_ms,
            latency_badge,
            delivery_status,
            webhook_status_code,
            webhook_attempts,
        }
    }
}

