/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemDetailResponse : Envelope returned by item detail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemDetailResponse {
    #[serde(rename = "item")]
    pub item: Box<models::VintedItemDetail>,
    #[serde(rename = "market")]
    pub market: String,
}

impl ItemDetailResponse {
    /// Envelope returned by item detail.
    pub fn new(item: models::VintedItemDetail, market: String) -> ItemDetailResponse {
        ItemDetailResponse {
            item: Box::new(item),
            market,
        }
    }
}

