/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchResponse : Envelope returned by search and search_by_image.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::VintedItemSummary>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::VintedPagination>,
    #[serde(rename = "market")]
    pub market: String,
    #[serde(rename = "seller_country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seller_country: Option<Option<String>>,
}

impl SearchResponse {
    /// Envelope returned by search and search_by_image.
    pub fn new(items: Vec<models::VintedItemSummary>, pagination: models::VintedPagination, market: String) -> SearchResponse {
        SearchResponse {
            items,
            pagination: Box::new(pagination),
            market,
            seller_country: None,
        }
    }
}

