/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StreamMonitorUpdate : Partial update stream monitor request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamMonitorUpdate {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "usernames", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub usernames: Option<Option<Vec<String>>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "webhook_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
    #[serde(rename = "webhook_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
    #[serde(rename = "filter_types", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filter_types: Option<Option<Vec<String>>>,
}

impl StreamMonitorUpdate {
    /// Partial update stream monitor request.
    pub fn new() -> StreamMonitorUpdate {
        StreamMonitorUpdate {
            name: None,
            usernames: None,
            status: None,
            webhook_url: None,
            webhook_secret: None,
            filter_types: None,
        }
    }
}

