/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StreamMonitorListResponse : Paginated list of stream monitors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamMonitorListResponse {
    #[serde(rename = "monitors")]
    pub monitors: Vec<models::StreamMonitorResponse>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "page_size")]
    pub page_size: i32,
}

impl StreamMonitorListResponse {
    /// Paginated list of stream monitors.
    pub fn new(monitors: Vec<models::StreamMonitorResponse>, total: i32, page: i32, page_size: i32) -> StreamMonitorListResponse {
        StreamMonitorListResponse {
            monitors,
            total,
            page,
            page_size,
        }
    }
}

