/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TweetDeliveryLogResponse : Tweet delivery log entry.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TweetDeliveryLogResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "monitor_id")]
    pub monitor_id: String,
    #[serde(rename = "monitor_name")]
    pub monitor_name: String,
    #[serde(rename = "tweet_id")]
    pub tweet_id: String,
    #[serde(rename = "author_username")]
    pub author_username: String,
    #[serde(rename = "tweet_text_preview", deserialize_with = "Option::deserialize")]
    pub tweet_text_preview: Option<String>,
    #[serde(rename = "tweet_url")]
    pub tweet_url: String,
    #[serde(rename = "tweet_published_at")]
    pub tweet_published_at: String,
    #[serde(rename = "detected_at")]
    pub detected_at: String,
    #[serde(rename = "latency_ms")]
    pub latency_ms: i32,
    #[serde(rename = "latency_badge")]
    pub latency_badge: String,
    #[serde(rename = "delivery_status")]
    pub delivery_status: String,
    #[serde(rename = "webhook_status_code", deserialize_with = "Option::deserialize")]
    pub webhook_status_code: Option<i32>,
    #[serde(rename = "webhook_attempts")]
    pub webhook_attempts: i32,
}

impl TweetDeliveryLogResponse {
    /// Tweet delivery log entry.
    pub fn new(id: String, monitor_id: String, monitor_name: String, tweet_id: String, author_username: String, tweet_text_preview: Option<String>, tweet_url: String, tweet_published_at: String, detected_at: String, latency_ms: i32, latency_badge: String, delivery_status: String, webhook_status_code: Option<i32>, webhook_attempts: i32) -> TweetDeliveryLogResponse {
        TweetDeliveryLogResponse {
            id,
            monitor_id,
            monitor_name,
            tweet_id,
            author_username,
            tweet_text_preview,
            tweet_url,
            tweet_published_at,
            detected_at,
            latency_ms,
            latency_badge,
            delivery_status,
            webhook_status_code,
            webhook_attempts,
        }
    }
}

