/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VintedPagination : Page metadata. Resend `time` to page a search deterministically.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VintedPagination {
    #[serde(rename = "current_page")]
    pub current_page: i32,
    #[serde(rename = "total_pages")]
    pub total_pages: i32,
    #[serde(rename = "total_entries")]
    pub total_entries: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
    #[serde(rename = "time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time: Option<Option<i32>>,
}

impl VintedPagination {
    /// Page metadata. Resend `time` to page a search deterministically.
    pub fn new(current_page: i32, total_pages: i32, total_entries: i32, per_page: i32) -> VintedPagination {
        VintedPagination {
            current_page,
            total_pages,
            total_entries,
            per_page,
            time: None,
        }
    }
}

