/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VintedImageSearchRequest : Search by exactly one public image URL or base64-encoded image.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VintedImageSearchRequest {
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "image_base64", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_base64: Option<Option<String>>,
    /// Vinted market code; uk aliases gb
    #[serde(rename = "market", skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "per_page", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i32>,
    #[serde(rename = "price_from", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_from: Option<Option<f64>>,
    #[serde(rename = "price_to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_to: Option<Option<f64>>,
    #[serde(rename = "brand_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_ids: Option<Option<String>>,
    #[serde(rename = "catalog_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub catalog_ids: Option<Option<String>>,
    #[serde(rename = "color_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color_ids: Option<Option<String>>,
    #[serde(rename = "size_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size_ids: Option<Option<String>>,
    #[serde(rename = "material_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub material_ids: Option<Option<String>>,
    #[serde(rename = "status_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_ids: Option<Option<String>>,
    #[serde(rename = "time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time: Option<Option<i32>>,
    #[serde(rename = "search_session_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub search_session_id: Option<Option<String>>,
}

impl VintedImageSearchRequest {
    /// Search by exactly one public image URL or base64-encoded image.
    pub fn new() -> VintedImageSearchRequest {
        VintedImageSearchRequest {
            image_url: None,
            image_base64: None,
            market: None,
            page: None,
            per_page: None,
            price_from: None,
            price_to: None,
            brand_ids: None,
            catalog_ids: None,
            color_ids: None,
            size_ids: None,
            material_ids: None,
            status_ids: None,
            time: None,
            search_session_id: None,
        }
    }
}

