/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VintedItemDetail : A single listing with the fields only the detail endpoint carries.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VintedItemDetail {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "price")]
    pub price: Box<models::VintedPrice>,
    #[serde(rename = "brand_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_title: Option<Option<String>>,
    #[serde(rename = "display_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_title: Option<Option<String>>,
    #[serde(rename = "display_subtitle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_subtitle: Option<Option<String>>,
    #[serde(rename = "size_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size_title: Option<Option<String>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "is_visible", skip_serializing_if = "Option::is_none")]
    pub is_visible: Option<bool>,
    #[serde(rename = "promoted", skip_serializing_if = "Option::is_none")]
    pub promoted: Option<bool>,
    #[serde(rename = "favourite_count", skip_serializing_if = "Option::is_none")]
    pub favourite_count: Option<i32>,
    #[serde(rename = "view_count", skip_serializing_if = "Option::is_none")]
    pub view_count: Option<i32>,
    #[serde(rename = "service_fee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_fee: Option<Option<String>>,
    #[serde(rename = "total_item_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_item_price: Option<Option<String>>,
    #[serde(rename = "content_source", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_source: Option<Option<String>>,
    #[serde(rename = "seller_country_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seller_country_code: Option<Option<String>>,
    #[serde(rename = "similarity_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub similarity_score: Option<Option<f64>>,
    #[serde(rename = "user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user: Option<Option<Box<models::VintedUserSummary>>>,
    #[serde(rename = "photo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub photo: Option<Option<Box<models::VintedPhoto>>>,
    #[serde(rename = "photos", skip_serializing_if = "Option::is_none")]
    pub photos: Option<Vec<models::VintedPhoto>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "catalog_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub catalog_id: Option<Option<i32>>,
    #[serde(rename = "color1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color1: Option<Option<String>>,
    #[serde(rename = "color2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color2: Option<Option<String>>,
    #[serde(rename = "package_size_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_size_id: Option<Option<i32>>,
    #[serde(rename = "is_favourite", skip_serializing_if = "Option::is_none")]
    pub is_favourite: Option<bool>,
    #[serde(rename = "can_buy", skip_serializing_if = "Option::is_none")]
    pub can_buy: Option<bool>,
    #[serde(rename = "can_bundle", skip_serializing_if = "Option::is_none")]
    pub can_bundle: Option<bool>,
    #[serde(rename = "can_reserve", skip_serializing_if = "Option::is_none")]
    pub can_reserve: Option<bool>,
    #[serde(rename = "instant_buy", skip_serializing_if = "Option::is_none")]
    pub instant_buy: Option<bool>,
    #[serde(rename = "is_hidden", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<bool>,
    #[serde(rename = "is_reserved", skip_serializing_if = "Option::is_none")]
    pub is_reserved: Option<bool>,
    #[serde(rename = "is_closed", skip_serializing_if = "Option::is_none")]
    pub is_closed: Option<bool>,
    #[serde(rename = "seller", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seller: Option<Option<Box<models::VintedSellerSummary>>>,
    #[serde(rename = "size_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size_id: Option<Option<i32>>,
    #[serde(rename = "status_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_id: Option<Option<i32>>,
    #[serde(rename = "brand_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_id: Option<Option<i32>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Vec<String>>,
    #[serde(rename = "upload_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upload_date: Option<Option<String>>,
    #[serde(rename = "uploaded_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uploaded_at: Option<Option<String>>,
}

impl VintedItemDetail {
    /// A single listing with the fields only the detail endpoint carries.
    pub fn new(id: i32, title: String, price: models::VintedPrice, url: String) -> VintedItemDetail {
        VintedItemDetail {
            id,
            title,
            price: Box::new(price),
            brand_title: None,
            display_title: None,
            display_subtitle: None,
            size_title: None,
            status: None,
            url,
            path: None,
            is_visible: None,
            promoted: None,
            favourite_count: None,
            view_count: None,
            service_fee: None,
            total_item_price: None,
            content_source: None,
            seller_country_code: None,
            similarity_score: None,
            user: None,
            photo: None,
            photos: None,
            description: None,
            catalog_id: None,
            color1: None,
            color2: None,
            package_size_id: None,
            is_favourite: None,
            can_buy: None,
            can_bundle: None,
            can_reserve: None,
            instant_buy: None,
            is_hidden: None,
            is_reserved: None,
            is_closed: None,
            seller: None,
            size_id: None,
            status_id: None,
            brand_id: None,
            category: None,
            upload_date: None,
            uploaded_at: None,
        }
    }
}

