/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VintedSellerSummary : Richer seller block carried on item detail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VintedSellerSummary {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<String>,
    #[serde(rename = "photo_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub photo_url: Option<Option<String>>,
    #[serde(rename = "business", skip_serializing_if = "Option::is_none")]
    pub business: Option<bool>,
    #[serde(rename = "feedback_count", skip_serializing_if = "Option::is_none")]
    pub feedback_count: Option<i32>,
    #[serde(rename = "feedback_reputation", skip_serializing_if = "Option::is_none")]
    pub feedback_reputation: Option<f64>,
    #[serde(rename = "item_count", skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
    #[serde(rename = "location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location: Option<Option<String>>,
    #[serde(rename = "last_seen", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<Option<String>>,
    #[serde(rename = "badges", skip_serializing_if = "Option::is_none")]
    pub badges: Option<Vec<String>>,
}

impl VintedSellerSummary {
    /// Richer seller block carried on item detail.
    pub fn new(id: i32) -> VintedSellerSummary {
        VintedSellerSummary {
            id,
            login: None,
            photo_url: None,
            business: None,
            feedback_count: None,
            feedback_reputation: None,
            item_count: None,
            location: None,
            last_seen: None,
            badges: None,
        }
    }
}

