/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VintedPhoto : One item photo.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VintedPhoto {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "dominant_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dominant_color: Option<Option<String>>,
    #[serde(rename = "is_main", skip_serializing_if = "Option::is_none")]
    pub is_main: Option<bool>,
    #[serde(rename = "width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<i32>>,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<i32>>,
    #[serde(rename = "full_size_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub full_size_url: Option<Option<String>>,
}

impl VintedPhoto {
    /// One item photo.
    pub fn new(id: i32, url: String) -> VintedPhoto {
        VintedPhoto {
            id,
            url,
            dominant_color: None,
            is_main: None,
            width: None,
            height: None,
            full_size_url: None,
        }
    }
}

