/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookListResponse : List of webhooks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookListResponse {
    #[serde(rename = "webhooks")]
    pub webhooks: Vec<models::WebhookListItem>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl WebhookListResponse {
    /// List of webhooks.
    pub fn new(webhooks: Vec<models::WebhookListItem>, total: i32) -> WebhookListResponse {
        WebhookListResponse {
            webhooks,
            total,
        }
    }
}

