/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookCreate : Configure webhook on a monitor.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCreate {
    #[serde(rename = "monitor_id")]
    pub monitor_id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret: Option<Option<String>>,
}

impl WebhookCreate {
    /// Configure webhook on a monitor.
    pub fn new(monitor_id: String, url: String) -> WebhookCreate {
        WebhookCreate {
            monitor_id,
            url,
            secret: None,
        }
    }
}

