/*
 * ScrapeBadger API
 *
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookTestRequest : Test webhook delivery request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookTestRequest {
    /// Monitor with webhook to test
    #[serde(rename = "monitor_id")]
    pub monitor_id: String,
}

impl WebhookTestRequest {
    /// Test webhook delivery request.
    pub fn new(monitor_id: String) -> WebhookTestRequest {
        WebhookTestRequest {
            monitor_id,
        }
    }
}

